#!/usr/bin/env bash
# this script displays numbers 1 to 100, and identifies multiples of some numbers

count=1

while [[ "$count" -le 100 ]]; do
	if [ $((count%15)) -eq 0 ]; then
	echo "FizzBuzz"
	count=$((count + 1))
elif [ $((count%3)) -eq 0 ]; then
	echo "Fizz"
	count=$((count + 1))
elif [ $((count%5)) -eq 0 ]; then
	echo "Buzz"
	count=$((count + 1))
else
	echo "$count"
	count=$((count + 1))
fi
done
