#!/usr/bin/env bash
# this script uses an 'if' statement and 'while' to display messages

count=1

while [ "$count" -le 10 ]; do
	if [ "$count" = 9 ]; then
		echo "Best School"
		echo "Hi"
		count=$((count + 1))
	else
			echo "Best School"
			count=$((count + 1))
	fi
done
