#!/usr/bin/env bash
# this script uses case to display numbers and warn of bad luck

count=1

while [[ "$count" -le 20 ]]; do
	case "$count" in
		4) 	echo "$count"
			echo "bad luck from China"
			count=$((count + 1))
			;;
		9)	echo "$count"
			echo "bad luck from Japan"
			count=$((count + 1))
			;;
		17)	echo "$count"
			echo "bad luck from Italy"
			count=$((count + 1))
			;;
		*)	echo "$count"
			count=$((count + 1))
			;;
	esac
done

