#!/usr/bin/env bash
# this script uses a for loop to display the content of the current directory in list format (only the part after the first dash)

LIST="$(ls)"
for i in $LIST; do
	echo "$i" | cut -d "-" -f 2-
done
