#!/usr/bin/env bash
# this script gives information about the file 'school'

FILE=./school

if [ -e "$FILE" ]; then
	if [ -s "$FILE" ]; then
		echo "school file exists"
		echo "school file is not empty"
	else
		echo "school file exists"
		echo "school file is empty"
	fi
	if [ -f "$FILE" ]; then
		echo "school is a regular file"
	fi
else
	echo "school file does not exist"
	exit 1
fi 
